name: dummy_products
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management
  flutter_bloc: ^8.1.0

  # Networking and API
  dio: ^5.0.0
  retrofit: ^4.0.1

  # Data Caching
  hive_flutter: ^1.1.0

  # Immutable Data Models
  freezed_annotation: ^2.1.0
  json_serializable: ^6.1.5
  json_annotation: ^4.9.0

  # Dependency Injection
  get_it: ^7.2.0

  # Dartz (Functional programming, for Either)
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.0
  freezed: ^2.1.0
  retrofit_generator: ^8.2.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
